// utils/careers.ts

export const careers = [
    { title: "Software Engineer", description: "Develop and maintain software applications daily.", traits: ["analytical", "problem-solving", "technical"] },
    { title: "Data Scientist", description: "Analyze and interpret data for valuable insights.", traits: ["analytical", "data-driven", "scientific"] },
    { title: "Graphic Designer", description: "Create visual designs for various media projects.", traits: ["creative", "visual", "technical"] },
    { title: "Marketing Specialist", description: "Plan and execute marketing strategies for brands.", traits: ["strategic", "people-oriented", "communicative"] },
    { title: "Teacher", description: "Educate and mentor students on various subjects.", traits: ["people-oriented", "communicative", "empathetic"] },
    { title: "Financial Analyst", description: "Analyze financial data to help make key decisions.", traits: ["analytical", "detail-oriented", "data-driven"] },
    { title: "Psychologist", description: "Support individuals with mental health challenges.", traits: ["empathetic", "communicative", "problem-solving"] },
    { title: "Architect", description: "Design and oversee the construction of buildings.", traits: ["creative", "visual", "analytical", "technical"] },
    { title: "Chef", description: "Prepare and create innovative culinary dishes.", traits: ["creative", "hands-on", "detail-oriented"] },
    { title: "Human Resource", description: "Manage employee relations and organizational culture.", traits: ["people-oriented", "empathetic", "communicative"] },
    { title: "Mechanical Engineer", description: "Design and develop complex mechanical systems.", traits: ["analytical", "hands-on", "problem-solving", "technical"] },
    { title: "Civil Engineer", description: "Plan and design infrastructure projects and systems.", traits: ["analytical", "detail-oriented", "problem-solving"] },
    { title: "Nurse", description: "Provide medical care and assist healthcare teams.", traits: ["empathetic", "communicative", "people-oriented", "detail-oriented"] },
    { title: "Entrepreneur", description: "Create and grow a business or innovative venture.", traits: ["strategic", "risk-taking", "creative"] },
    { title: "Environmental Scientist", description: "Develop solutions to address environmental issues.", traits: ["analytical", "nature-oriented", "scientific", "problem-solving"] },
    { title: "Content Writer", description: "Write, edit, and create engaging content online.", traits: ["communicative", "creative", "curious"] },
    { title: "Product Manager", description: "Lead product development and ensure its success.", traits: ["strategic", "people-oriented", "analytical", "problem-solving"] },
    { title: "Veterinarian", description: "Provide care and treatment for animals' health.", traits: ["empathetic", "nature-oriented", "scientific"] },
    { title: "Event Planner", description: "Organize and execute memorable events effectively.", traits: ["people-oriented", "detail-oriented", "creative"] },
    { title: "Pharmacist", description: "Prepare medications and provide patient counseling.", traits: ["detail-oriented", "analytical", "scientific"] },
    { title: "Cybersecurity", description: "Protect systems and networks from cyber threats.", traits: ["analytical", "detail-oriented", "problem-solving", "technical"] },
    { title: "Electrical Engineer", description: "Design and maintain innovative electrical systems.", traits: ["analytical", "hands-on", "problem-solving", "technical"] },
    { title: "Social Worker", description: "Support individuals facing personal life challenges.", traits: ["empathetic", "people-oriented", "communicative"] },
    { title: "Physician", description: "Diagnose and treat illnesses to improve health.", traits: ["analytical", "empathetic", "problem-solving", "scientific"] },
    { title: "Web Developer", description: "Build websites and optimize them for functionality.", traits: ["analytical", "creative", "technical", "problem-solving"] },
    { title: "Lawyer", description: "Provide expert legal advice and representation.", traits: ["communicative", "analytical", "detail-oriented"] },
    { title: "Biotechnologist", description: "Use biological research for industrial applications.", traits: ["analytical", "scientific", "problem-solving"] },
    { title: "Research Scientist", description: "Conduct experiments to explore scientific questions.", traits: ["scientific", "analytical", "detail-oriented"] },
    { title: "Accountant", description: "Manage financial records and ensure accurate reports.", traits: ["detail-oriented", "analytical", "data-driven"] },
    { title: "Physical Therapist", description: "Help patients regain mobility and physical function.", traits: ["empathetic", "hands-on", "people-oriented"] },
    { title: "Electrician", description: "Install and repair electrical systems and devices.", traits: ["hands-on", "analytical", "problem-solving"] },
    { title: "Pilot", description: "Operate and safely navigate various types of aircraft.", traits: ["detail-oriented", "analytical", "calm-under-pressure"] },
    { title: "Journalist", description: "Investigate and report news stories for the public.", traits: ["curious", "communicative", "detail-oriented"] },
    { title: "Philosopher", description: "Explore deep questions about life and knowledge.", traits: ["analytical", "creative", "curious"] },
    { title: "Public Relations", description: "Manage communication strategies for public relations.", traits: ["communicative", "strategic", "people-oriented"] },
    { title: "Surgeon", description: "Perform operations to treat injuries or diseases.", traits: ["detail-oriented", "analytical", "calm-under-pressure", "scientific"] },
    { title: "Dentist", description: "Care for oral health and treat dental conditions.", traits: ["detail-oriented", "analytical", "empathetic", "scientific"] },
    { title: "Marine Biologist", description: "Study marine organisms and their environments.", traits: ["scientific", "nature-oriented", "curious"] },
    { title: "Video Game Developer", description: "Design, develop, and test interactive video games.", traits: ["creative", "problem-solving", "technical"] },
];

export const questions = [
    { question: "Do you enjoy working with data?", options: ["Yes", "No"], trait: "data-driven" },
    { question: "Are you interested in designing visuals?", options: ["Yes", "No"], trait: "creative" },
    { question: "Do you like solving complex problems?", options: ["Yes", "No"], trait: "problem-solving" },
    { question: "Are you good at communication?", options: ["Yes", "No"], trait: "communicative" },
    { question: "Do you enjoy teaching or mentoring?", options: ["Yes", "No"], trait: "people-oriented" },
    { question: "Do you have a keen eye for detail?", options: ["Yes", "No"], trait: "detail-oriented" },
    { question: "Do you like to work with your hands?", options: ["Yes", "No"], trait: "hands-on" },
    { question: "Do you enjoy interacting with people daily?", options: ["Yes", "No"], trait: "people-oriented" },
    { question: "Are you interested in starting your own business?", options: ["Yes", "No"], trait: "risk-taking" },
    { question: "Do you care about environmental issues?", options: ["Yes", "No"], trait: "nature-oriented" },
    { question: "Are you interested in animal care?", options: ["Yes", "No"], trait: "empathetic" },
    { question: "Are you curious about finance and investing?", options: ["Yes", "No"], trait: "data-driven" },
    { question: "Do you enjoy writing and storytelling?", options: ["Yes", "No"], trait: "creative" },
    { question: "Do you have an interest in health sciences?", options: ["Yes", "No"], trait: "empathetic" },
    { question: "Are you calm under pressure?", options: ["Yes", "No"], trait: "calm-under-pressure" },
    { question: "Do you like working with children?", options: ["Yes", "No"], trait: "empathetic" },
    { question: "Do you enjoy working with technology?", options: ["Yes", "No"], trait: "technical" },
    { question: "Are you interested in marine life?", options: ["Yes", "No"], trait: "nature-oriented" },
    { question: "Do you enjoy working with data and solving puzzles?", options: ["Yes", "No"], trait: "analytical" },
    { question: "Do you like working with technology and coding?", options: ["Yes", "No"], trait: "technical" },
    { question: "Are you good at explaining complex ideas to others?", options: ["Yes", "No"], trait: "communicative" },
];
