// utils/careers.ts

export const careers = [
    { title: "Software Engineer", description: "Develop and maintain software applications.", traits: ["analytical", "problem-solving", "technical"] },
    { title: "Data Scientist", description: "Analyze data to extract meaningful insights.", traits: ["analytical", "data-driven", "scientific"] },
    { title: "Graphic Designer", description: "Design visual content for digital and print media.", traits: ["creative", "visual", "technical"] },
    { title: "Marketing Specialist", description: "Create marketing strategies to promote products.", traits: ["strategic", "people-oriented", "communicative"] },
    { title: "Teacher", description: "Educate students on specific subjects.", traits: ["people-oriented", "communicative", "empathetic"] },
    { title: "Financial Analyst", description: "Analyze financial data and trends to provide business insights.", traits: ["analytical", "detail-oriented", "data-driven"] },
    { title: "Psychologist", description: "Help individuals understand and overcome mental health challenges.", traits: ["empathetic", "communicative", "problem-solving"] },
    { title: "Architect", description: "Design and plan buildings and structures.", traits: ["creative", "visual", "analytical", "technical"] },
    { title: "Chef", description: "Create and prepare culinary dishes.", traits: ["creative", "hands-on", "detail-oriented"] },
    { title: "Human Resources Specialist", description: "Manage employee relations and organizational culture.", traits: ["people-oriented", "empathetic", "communicative"] },
    { title: "Mechanical Engineer", description: "Design and develop mechanical systems.", traits: ["analytical", "hands-on", "problem-solving", "technical"] },
    { title: "Civil Engineer", description: "Plan, design, and oversee construction of infrastructure projects.", traits: ["analytical", "detail-oriented", "problem-solving"] },
    { title: "Nurse", description: "Provide patient care and assist in medical procedures.", traits: ["empathetic", "communicative", "people-oriented", "detail-oriented"] },
    { title: "Entrepreneur", description: "Start and manage your own business or venture.", traits: ["strategic", "risk-taking", "creative"] },
    { title: "Environmental Scientist", description: "Research and develop solutions to environmental issues.", traits: ["analytical", "nature-oriented", "scientific", "problem-solving"] },
    { title: "Content Writer", description: "Write and edit content for various platforms.", traits: ["communicative", "creative", "curious"] },
    { title: "Product Manager", description: "Oversee product development and ensure market fit.", traits: ["strategic", "people-oriented", "analytical", "problem-solving"] },
    { title: "Veterinarian", description: "Provide medical care to animals.", traits: ["empathetic", "nature-oriented", "scientific"] },
    { title: "Event Planner", description: "Organize and plan events.", traits: ["people-oriented", "detail-oriented", "creative"] },
    { title: "Pharmacist", description: "Prepare and dispense medications.", traits: ["detail-oriented", "analytical", "scientific"] },
    { title: "Cybersecurity Specialist", description: "Protect computer systems from cyber threats.", traits: ["analytical", "detail-oriented", "problem-solving", "technical"] },
    { title: "Electrical Engineer", description: "Design and develop electrical systems.", traits: ["analytical", "hands-on", "problem-solving", "technical"] },
    { title: "Social Worker", description: "Support individuals facing social and personal challenges.", traits: ["empathetic", "people-oriented", "communicative"] },
    { title: "Physician", description: "Diagnose and treat medical conditions.", traits: ["analytical", "empathetic", "problem-solving", "scientific"] },
    { title: "Web Developer", description: "Build and maintain websites and web applications.", traits: ["analytical", "creative", "technical", "problem-solving"] },
    { title: "Lawyer", description: "Provide legal advice and representation.", traits: ["communicative", "analytical", "detail-oriented"] },
    { title: "Biotechnologist", description: "Use biological processes for industrial applications.", traits: ["analytical", "scientific", "problem-solving"] },
    { title: "Research Scientist", description: "Conduct experiments to advance scientific knowledge.", traits: ["scientific", "analytical", "detail-oriented"] },
    { title: "Accountant", description: "Manage financial records and transactions.", traits: ["detail-oriented", "analytical", "data-driven"] },
    { title: "Physical Therapist", description: "Help patients recover physical function.", traits: ["empathetic", "hands-on", "people-oriented"] },
    { title: "Electrician", description: "Install and maintain electrical systems.", traits: ["hands-on", "analytical", "problem-solving"] },
    { title: "Pilot", description: "Operate and navigate aircraft.", traits: ["detail-oriented", "analytical", "calm-under-pressure"] },
    { title: "Journalist", description: "Report news and write articles.", traits: ["curious", "communicative", "detail-oriented"] },
    { title: "Philosopher", description: "Explore fundamental questions about existence and knowledge.", traits: ["analytical", "creative", "curious"] },
    { title: "Public Relations Specialist", description: "Manage an organization’s public image.", traits: ["communicative", "strategic", "people-oriented"] },
    { title: "Surgeon", description: "Perform surgical procedures to treat injuries and diseases.", traits: ["detail-oriented", "analytical", "calm-under-pressure", "scientific"] },
    { title: "Dentist", description: "Diagnose and treat dental conditions.", traits: ["detail-oriented", "analytical", "empathetic", "scientific"] },
    { title: "Marine Biologist", description: "Study marine organisms and ecosystems.", traits: ["scientific", "nature-oriented", "curious"] },
    { title: "Video Game Developer", description: "Design and create video games.", traits: ["creative", "problem-solving", "technical"] },
];

export const questions = [
    { question: "Do you enjoy working with data?", options: ["Yes", "No"], trait: "data-driven" },
    { question: "Are you interested in designing visuals?", options: ["Yes", "No"], trait: "creative" },
    { question: "Do you like solving complex problems?", options: ["Yes", "No"], trait: "problem-solving" },
    { question: "Are you good at communication?", options: ["Yes", "No"], trait: "communicative" },
    { question: "Do you enjoy teaching or mentoring?", options: ["Yes", "No"], trait: "people-oriented" },
    { question: "Do you have a keen eye for detail?", options: ["Yes", "No"], trait: "detail-oriented" },
    { question: "Do you like to work with your hands?", options: ["Yes", "No"], trait: "hands-on" },
    { question: "Do you enjoy interacting with people daily?", options: ["Yes", "No"], trait: "people-oriented" },
    { question: "Are you interested in starting your own business?", options: ["Yes", "No"], trait: "risk-taking" },
    { question: "Do you care about environmental issues?", options: ["Yes", "No"], trait: "nature-oriented" },
    { question: "Are you interested in animal care?", options: ["Yes", "No"], trait: "empathetic" },
    { question: "Are you curious about finance and investing?", options: ["Yes", "No"], trait: "data-driven" },
    { question: "Do you enjoy writing and storytelling?", options: ["Yes", "No"], trait: "creative" },
    { question: "Do you have an interest in health sciences?", options: ["Yes", "No"], trait: "empathetic" },
    { question: "Are you calm under pressure?", options: ["Yes", "No"], trait: "calm-under-pressure" },
    { question: "Do you like working with children?", options: ["Yes", "No"], trait: "empathetic" },
    { question: "Do you enjoy working with technology?", options: ["Yes", "No"], trait: "technical" },
    { question: "Are you interested in marine life?", options: ["Yes", "No"], trait: "nature-oriented" },
    { question: "Do you enjoy working with data and solving puzzles?", options: ["Yes", "No"], trait: "analytical" },
    { question: "Do you like working with technology and coding?", options: ["Yes", "No"], trait: "technical" },
    { question: "Are you good at explaining complex ideas to others?", options: ["Yes", "No"], trait: "communicative" },
];
